<font size="4"><b>History</b></font>

<br />

<p><font color="gray" face="microsoft sans serif"> 

        The idea of this tournament back in 1987 came from the genesis of Holy Cross high school principal Mr. Robert Dejulius , Mr. Bert LeChasseur and Mr. Frank Roberto who thought it would be a great experience for all of the Catholic High school boys and girls basketball teams to participate in. They wanted to have teams play each other from different levels and rekindle and renew old acquaintances and make new friendships.<br><br>

        This tournament is one of the largest basketball tournaments in Canada. The staff and students have done a brilliant job making the tournament memorable for all participants. Here are some of the tournament highlights over the years.<br><br>

        In 1988, in the tournament's first girl's rivalry, the Notre Dame Jugglers, led by Maureen MacPherson, defeated Holy Cross 64-44. In the boy's matchup Mark Van Der Zalm lead the Holy Cross team against a strong S.T.A. team. Defense was the key as Holy Cross defeated its rival 52-38, Highlighted by a terrific dance on the Friday night, this “Weekend” was a great success and everyone left the tournament looking forward to the next year.<br><br>

        1989 saw the tournament become not only an opportunity for athletes to compete, but now rivalries were developing. The S.T.A. Fighting Saints lived up to their names in 89 by upsetting S.T.M.C in the quarter finals. That set up what is still considered to be the most exciting game in the tournament to date, S.T.A versus Holy Cross. Strong rivalries were also developing on the girls Side of the draw. One of the tournament's best athletes ever, Lorraine Denis led her Holy Cross Crusaders to a 58-50 victory over Notre Dame.<br><br>

        The 1990 tournament was also exciting, all Catholic schools in the province were in attendance. However this was to be Notre Dame's year, Jenni Washburn, another perennially strong performer, lead the lady Jugglers to a 61-28 victory over St. Patrick's, Notre Dame boys relied on team discipline and a stifling 2-2-1 zone press to overcome Dennis Zimmerman and the rest of the S.T.M.C., Knights, 89-76.<br><br>

        In 1991, The Viray sisters, Leah Hernandez, and the feisty little guard from S.T.A named Jamie Mackey made for an exciting girls tournament. A young grade 10 student from L.F.A. Julie Kaulius led her team into the final against a fit team from St. Patrick's. In the end the Celtics proved to be a little too much for the young Angels.<br><br>

        The 1991 Boys Draw was perhaps the most competitive ever. The final ended up being a rematch of 1990. Adriano Ferrario held the hot hand for the Jugglers as once again Notre Dame's disciplined play overwhelmed the Knights from S.T.M.C.<br><br>

        In 1992, the Angels from L.F.A. avenged their loss to St. Pat's in the previous year by using strong inside play coupled with confident point play by Jeannette Guichon. Once again S.T.A. and Holy Cross brought the house alive with a thrilling overtime battle on Friday night. This time the Fighting Saints came out on top, and went on to finish second to Notre Dame led by sharp shooting guard and tournament MVP Mike Moretto.<br><br>

        Debbie Smallwood's L.F.A. Angels were on form in 1993. With a strong senior line-up, led by the Kanakos sisters, the Angels fought off competition to win a second straight championship. The boys final was exciting for the host school, as the final pitted Holy Cross against familiar rivals S.T.A. . Rhys Campbell from S.T.A. and Cinton Ho from Holy Cross put on a great show in the Crusaders' victory. A great team effort by the likes of Martin Kraemer, Blair Palm and Michael Roberts helped the Crusaders reclaim the title. 1994 was the year of the Fighting Saints. The girls team, captained by Jamie Mackey, fought hard for third place while the boys were once again in the championship, Notre Dame put up a good fight before the hard working , talented Fighting Saints ran away with the Boys title.<br><br>

        The Fighting Saints must have been teasing the competition for in 1995 they captured both titles. Both the boys and girls championship games were extremely intense. Stacy Duplis led the Fighting Saints women squad, while her male counterpart, Mike Bartos, showed tremendous focus in leading his team to the title.<br><br>

        The 1996 tournament was the L.F.A. Show. Debbie Smallwood's team, led by Mr. Prescott's favorite player, Genevieve Kettlewell, walked through the competition.The S.T.A. Fighting Saints looked strong in repeating with another Boys title over STM. 1997 saw the Holy Cross Crusaders capture both the Girls and Boys titles. Led by three seniors; Kris Starcznoyski, John Stocking and John McDonald, the Crusaders played a hard fought game against St. Thomas More. Tim Dumas Of the Knights played a particularly strong tournament. The Crusader women, led by Erin Mattson, played a good game against the always strong L.F.A Angels.<br><br>

        Vinny Dumas inspired the Knights of St. Thomas More in the 1998 Catholic Tournament to an exciting victory over STA. St. John Brebeuf played incredibly well and are going to be a force to be reckoned with, in the girls draw Aislinn Keegan played well for LFA and Archbishop Carney looked very strong for a young team. O'Grady made it to the semi-finals losing to eventual tournament winners, Holy Cross.<br><br>

        1999 saw Aislyn Keegan finish off her brilliant Catholic Tournament career by leading the LFA Angels back to the title. In the boys draw the O'Grady Totems pulled off the biggest upset in tournament history by defeating the talented Fighting Saints squad from STA. A young team on the horizon appears to be the Mustangs from Immaculata whose group of young ladies may surprise Some teams in the years to come.<br><br>

        Indeed the Lady Mustangs did surprise people in 2000. This young energetic team placed higher than any other time in their history. The girls final was an upset as the Holy Cross Crusaders, led by Chrissy Dumas and Jennifer Padrinao, toppled the powerful Angels from Little Flower Academy. Emily Cordonier and Heidi Flores played brilliantly and will be back to lead the Angels in 2001. The boys draw was dominated by a very powerful STA Fighting Saints team. Sean Thistle was an awesome force in the middle and was well deserving of the MVP. St. Pat's Celtics appear to be a team on the rise and definitely will be a contender in years to come.<br><br>

        The 2001 tournament was the biggest ever, with a total of 23 teams. The girls final continued an excellent rivalry, with LFA and Holy Cross doing battle for the fourth time in five years. The Crusaders, led by Taylor Stuart and Stephanie Hibbert went toe to toe with three-year senior Heidi Flores and Emily Cordonier. Despite a late surge by the Angels, the Crusaders came out on top in an intense game. The Lady Mustangs once again showed well, and the tournament was pleased to welcome for the first time the STMC Knights Senior Girls Team. The boys final was a spirited affair, as it always is when Holy Cross and STM meet. A very athletic and talented team from STM came out the winner over a young Holy Cross Squad.<br><br>

        In 2002, history looked to repeat itself, as the Holy Cross girls and the Little Flower Academy girls renewed their rivalry. This time though, the LFA girls, led by Lauren Labrosse and Carolyn Cannon, emerged victorious in one of the most thrilling finals in the history of the tournament. LFA had to battle through adversity as they went to overtime the night before, beating a spirited Immaculata Lady Mustangs squad. The boys draw saw the Archbishop Carney Stars, led by David Geary, Collect the first Catholics banner in the short history of the school, as they handed defeat to the second place Jugglers of Notre Dame. The St. John Brebeuf Bears had a best ever finish, as they took third place, led by MVP Michael Short.<br><br>

        The 2003 tournament was one of many firsts. It saw an excellent girls team from Immaculata led by Kyla Jones capture their first ever title with impressive wins over Little Flower Academy and Holy Cross in the finals. The Lady Mustangs became the first team to win the tournament from outside the lower mainland. On the boys side of the draw many games were closely contested but in the end it was the "run in gun" show from St. Pats that led the way. Tournament M.V.P Patrick Caffrey led his team in an exciting final over defending Champions Archbishop Carney. This was also St. Pat's boys team first B.C. Catholic Championship.<br><br>

        In 2004, the tournament saw another great battle repeat on the girls side from the year before with Immaculata and LFA in a fight to the finish. Once again Immaculata Mustangs led by Katie Woodman defeated the LFA Angels headed by Caroline Cannon. On the boys side of the draw the Notre Dame Jugglers were seen as the strong favorite depending largely on the leadership of their seniors. STM Knights, on the other hand, came to battle, with Graeme Moore and Lenny Piprah leading the way. In the end, the Knights became victorious defeating the Jugglers by three, in a very exciting Catholic final.<br><br>

        2005 would see the Angels exact a measure of revenge on the Mustangs. Little Flower came to the final having lost the last two to Immaculata, and were looking to turn the tide. Led by Liz Cordonier, they did just that, as they battled to a 54-36 victory. The boys side was another rematch, as the veteran Jugglers would battle a talented but inexperienced group of Knights from STM. In the end, the veteran leadership of Antonio Sorace and Alan Hogan would lead Notre Dame to a 59-46 win.<br><br>

        In 2006 old rivalries were rekindled. The Knights of STM faced the Crusaders of Holy Cross in the boys final for the fourth time in Catholics’ history. This year’s edition of the Knights proved too talented, as they convincingly defeated the Crusaders for the fifth BC Catholic title. The girls final pitted Holy Cross against Little Flower Academy for the sixth time in the last ten years. In a back and forth affair, the Angels pulled away in the fourth quarter to repeat as BC Catholic Champions, and take their eighth title in tournament history.<br><br>

        2007 marked the 20th anniversary of the Catholics. The tournament was full of competitive games on the boys and girls sides. The boys' final was a well played affair which pitted STM against Notre Dame in the finals. STM prevailed 69-59.  The girls' final once again matched up old rivals Holy Cross and LFA and the Crusaders prevailed in a defensive battle 46-33.<br><br>

        2008 saw the return of a strong squad from Vancouver College to the Catholics. VC competed well and made the boys finals and triumphed over STM 56-36. VC was led by provincial all-star Marc Trasolini. The girls side of the draw saw Immaculata and Holy Cross reach the girls finals. The Holy Cross girls were led by the explosive speed and intensity of Megan Schaufele and the defensive presence of Amy Beauchamp, Holy Cross defeated Immaculata 54-39 in an exciting game.<br><br>

        In 2009 the tournament saw another great fight to the finish as Immaculata and Holy Cross battled their way to the finals. The girls final was an intense defensive battle until Holy Cross pulled away in the final 3 minutes to defeat Immaculata 41 - 32. The Crusaders were led by Bianca Palitti, Jeanneline Yngresso and Tessa Beauchamp. The boys side of the tournament saw many evenly competed games. Perennial powerhouse Vancouver College met St. Pats in the finals. In front of a packed house the Celtics of St. Pats were leading early in the 3rd quarter with their 3 point barrage putting a little scare into the Irish. Vancouver College's overall depth and senior leadership enabled them to see whether the storm and VC came out on top 67-47.<br><br>

        In 2010, there were many close hard fought games during the preliminary round of the BC Catholics. This year’s edition also marked a Catholic first as two ex Holy Cross students got engaged at halftime of the girls finals. In a thrilling girl's final, Holy Cross edged out St. Thomas More 50-47. The girls were led by a gutsy performance from Tessa Beauchamp and great defensive play from Jessica Villadiego. On the boys side once again it was a rematch from 2009 as St. Pat's took on Vancouver College, VC prevailed 78-54 and were led by Philip Scrubb and Sam Williams.<br><br>

        The 2011 BC Catholics saw many competitive games played on both sides of the draw. STA girls team pressed their way into the finals and the Holy Cross girls team was led by the superb play of their seniors. The two teams met in the finals and the Holy Cross girls would not be denied this evening. The girls were inspired by their captain Tessa Beauchamp's never quit attitude. Holy Cross defeated STA 56-22, On the boys side of the draw STM and Holy Cross met in the finals and both teams played before a packed house. The game was a close, hard fought battle and Holy Cross prevailed in overtime 53 - 46. The Crusaders were led by the play of seniors Richard Bos and Luke Ehman.<br><br>

        In 2012 the Tournament saw many exciting games played before enthusiastic crowds. The St. Anns boys team pulled off an opening round upset against the Holy Cross Crusaders. St. Anns also won the inaugural "Spirit Award" for their fun spirited cheers and overall zaniness. The boy's side of the draw saw Carney and STM meet in the finals and Carney prevailed 59-51 behind the leadership of William Baumann and Patrick Simon, On the girl's side of the draw Carney and Immaculata played an exciting semi-final game in which Carney won 39-38. The girls final saw an inspired Holy Cross team overwhelm Carney 45-32. Holy Cross was led by senior Michelle Zacharuk and grade 10's Michelle Bos, Amy Sprangers and Rachel Beauchamp.<br><br>

        The 2013 edition of the BC Catholics was memorable on many fronts. The tournament over the years has seen many games go into overtime but this year we had a 90 minute delay caused by a power outage. After the blackout, the tournament resumed with its usual tightly contested games. We also held our first ever skills and dunk contest that was well attended and well appreciated by the fans. In the second round of the boys side STM came up with a mild upset over Vancouver College. On the other side of the draw the Holy Cross Boys played tremendous defense and worked their way into the finals against STM. The finals were a well contested affair and the Crusaders beat STM 57-44. The girls side of the draw saw many close games and Holy Cross and STA met in the finals. STA battled with Holy Cross for most of the first half until Michele Bos and Nicole Van Der Helm helped the Crusaders open up a lead in the third quarter The Crusaders defeated STA 46 - 37.<br><br>

        The 2014 edition of the Catholics once again saw some amazing plays and fantastic finishes over the course of the 4 days. It seems every year more and more people attend and support the tournament and thus this provides the players the impetus to play and perform at a very high level. Right from the beginning of the tournament many close hard fought games were played. Many new and up and coming juniors and grade 11's played impressively and showed that the 2015 Catholics should be a very highly competitive tournament. Both the boys and girls finals pitted Holy Cross against STM. The Lady Crusaders were led by their Fab 5 group of grade 12's and they smothered the Knights 59-28 with a combination of in your face defense and precision accuracy on offense. On the boys side the Crusaders and the Knights battled it out in a closely contested affair until the Crusaders overall height advantage and defensive rebounding enabled them to pull away in the 4" quarter to a 58-48 victory.<br><br>

        The 2015 tournament saw the end of an impressive eight year run as champions for the Holy Cross Senior girls' BB program. The girls battled hard to overcome STM in an exciting overtime semifinal game. The girls' finals saw an extremely talented Immaculata team led by tournament MVP Emma Johnson play an aggressive pressing style of game which eventually wore out the Crusader girls and the final score was 76-41 The boys side of the draw saw many competitive games with Holy Cross and Vancouver College meeting in the boys' finals. Outstanding performances by V.C's Cam Beers, Rysen Johns ad Chris McAlpine help lead Vancouver College over a feisty Holy Cross team led by Taylor Browne and sharp shooting grade 11, Keegan Konn 66-53.<br><br>

        The 2016 version of the Catholics saw some very exciting games played. The boy’s side of the draw featured an overtime final between Holy Cross and Vancouver College. The Crusaders eventually defeated a stubborn Vancouver College team 63-60. Holy Cross was led by Keegan Konn, Nicholas Best and Marcus Browne. VC was led by their twin towers Rysen John and Sam Bailey. In an exciting girl’s final Immaculata. led by the inspired play of Ashlyn Day and the defensive presence of Nicole Hart were able to hold off STM by a score of 50-49.<br><br>

        At the 2017 rendition of the Catholics saw many competitive games on both sides of the draw however it was apparent from the beginning of the tournament that the Holy Cross Crusaders were on a collision course with their new nemesis ; Vancouver College Irish. The Crusaders played a brilliant team game throughout the hotly contested boys final and they defeated the “Irish” 66-54 . On the girls side Immaculata continued its impressive run led by Ashyln Day and Kate Johnson as they met the hard working Holy Cross Crusaders who came from behind to defeat STM in exciting overtime semifinal. The Mustangs were firing on all cylinders and they defeated the Crusaders 61-41.<br><br>

        2018 saw dominant performances throughout the tournament on the boys side by Vancouver College and Holy Cross. The two teams met in an epic battle and the “Irish” were led by all star shooting guard Jack Cruz Dumont , Callum Chow White and the all around hustle of Levi Devorak. Holy Cross was led by the high energy play of Jamal Osei - Amin , the sharp shooting of Gabe Takeaowa , Uyi Ologhola’s high flying end to end lay- ups and the outstanding two - way play and leadership of defensive mvp Michael Risi. The Crusaders and the Irish battled throughout an evenly played first half with the Vancouver College leading 26-24. The second half saw the Crusaders take a 46-41 lead at the end of the third quarter. Holy Cross stifled the Irish in the fourth quarter and pulled away to capture their third title in a row by a score of 62 - 51.<br><br>

        The girls side of the draw saw many competitive games and the final four saw STA play LFA and Holy Cross versus STM. STA defeated a freisty group of “Angels “ and won 61-54 . In the other semi final , the lady Crusaders gave it their all but came up a little short and lost 53 -44. The girls finals saw an exciting back and forth game with the first quarter ending with Aquinas leading 11-10. The rest of the game Aquinas was led by their “twin towers” of Olivia Thorpe and Jessica Clarke and STM couldn’t get the lead back and eventually lost 46-37. <br><br>

        2019 saw a “dominant performance” from the girls from St. Thomas Aquinas who were led by their grade 11 “twin towers” Jessica Clarke and Gemma Cutler who played an effective inside / outside game . They cruised through their side of the draw to play a “hot shooting team from LFA'' however their best wasn’t enough in the finals and STA defeated LFA by a margin of 72 -44 . The boys side once again saw a rematch of the Holy Cross Crusaders and Vancouver College Irish in the finals and it turned out to be another great and memorable game . The Crusaders were led by Micahel Risi’s unselfish play on both ends of the floor and Uyi Ologhola’s and Brent Padilla’s scoring in a see-saw battle against V.C’s Toni Maric and Callum Chow - White . The Crusader’s were down at halftime 24-21 but were able to prevail in the end 64-59 to capture their 4th straight championship. Jessica Clarke and Michael Risi were named tournament MVP’s.<br><br>

        2020 was another fun and competitive tournament . Once again the Crusaders and the Irish made their way to the finals and it didn't disappoint with another nail biter of a game where Holy Cross won a close game over VC 62-61 . This marked the end of an illustrious 4 year career at the Catholics by Uyi Ologhola .The Senior girls finals pitted the defending champions from STA against STM . Cassie Pennalosa led her team along with great defensive play from Tatiania Hughes and the exciting play of the Gaspar sisters defeated STA 51-36.<br><br>       

</p>
</font>